engines:
  duplication:
    enabled: true
    config:
      languages: "php"
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
        enabled: false
    config:
      file_extensions: "php"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"

ratings:
  paths:
    - "**.php"
    - "**.md"
