preset: recommended

risky: false

linting: true

enabled:
  - long_array_syntax
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - braces
  - indentation
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_trim
  - short_array_syntax
