css:
  tab-width: 4
  use-tabs: true
  print-width: 120
  double-quotes: true
    name: "*.css"

php:
  preset: recommended
  risky: false
  disabled:
    - braces
    - indentation
    - phpdoc_summary
    - phpdoc_to_comment
    - phpdoc_trim
  name: "*.php"
