sudo: required

language: php

matrix:
  include:
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTNAME="maelsoucaze/frenchlanguagepack"
    - SNIFF="1"
    - IMAGE_ICC="1"
    - EPV="1"
    - PHPBB_BRANCH="master"
    - PHPBB_VERSION="3.2"
    - PHPBB_LANGUAGE="fr"

branches:
  only:
    - master

# before_install:
#   - sudo mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE
#   - sudo mkdir -p $PHPBB_VERSION/en/language
#   - sudo mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
#   - sudo mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
#   - sudo mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
#   - git clone --branch $PHPBB_BRANCH "https://github.com/phpbb/phpbb.git"
#   - sudo mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language
#   - sudo mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
#   - curl -sS "https://getcomposer.org/installer" | php

install:
  - travis_retry composer install --dev --no-interaction --prefer-source
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
#   - php vendor/bin/PhpbbTranslationValidator.php validate $PHPBB_LANGUAGE --phpbb-version=$PHPBB_VERSION --display-notices
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTNAME/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
