language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

sudo: false

install:
  - composer install --no-interaction --prefer-source
  - git clone "https://github.com/phpbb/phpbb.git" --branch "master"
  - cp -R phpbb/phpBB/language/en/ phpBB/language/en/

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate --language-dir="phpBB/language" --phpbb-version="3.2" "fr" --display-notices

notifications:
  email: change
