sudo: false

language: php

php:
  - 5.5

matrix:
  fast_finish: true

env:
  global:
    - PHPBB_TAG="master"
    - PHPBB_VERSION="3.2"
    - PHPBB_LANGUAGE="fr"

before_install:
  - sudo mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE
  - sudo mkdir -p $PHPBB_VERSION/en/language
  - sudo mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
  - sudo mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
  - sudo mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
  - git clone --branch $PHPBB_TAG "https://github.com/phpbb/phpbb.git"
  - sudo mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language
  - sudo mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
  - curl -sS "https://getcomposer.org/installer" | php

install:
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate $PHPBB_LANGUAGE --phpbb-version=$PHPBB_VERSION --display-notices
  
notifications:
  email: change
